---
- hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: install Nginx
      apt:
        name: nginx
      tags: nginx

    - name: install PHP7.1, php7.1-fpm and additional components
      apt:
        name:
          - php7.1
          - php7.1-fpm
          - php7.1-xml
          - php7.1-mysqlnd
          - php7.1-curl
          - php7.1-imap
          - php7.1-gd
      tags: php

    - name: create Nginx configuration
      template:
        src: symfony-nginx.conf
        dest: /etc/nginx/sites-available/symfony.conf
      vars:
        socket: '/var/run/php/php7.1-fpm.sock'
      tags: nginx

    - name: symlink Nginx configuration
      file:
        src: /etc/nginx/sites-available/symfony.conf
        dest: /etc/nginx/sites-enabled/symfony.conf
        state: link
      tags: nginx

    - name: remove default Nginx configuration
      file:
        state: absent
        path: /etc/nginx/sites-enabled/default
      tags: nginx

    - name: restart Nginx
      service:
        name: nginx
        state: restarted
      tags: nginx
