---
- hosts: all
  become: true
  become_method: sudo

  vars:
    mysql_root_password: phpbench

  tasks:
    - name: install MySQL
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
      - python-mysqldb
      - mysql-server
    - name: create Mysql client connection data
      template:
        src: mysql-client.j2
        dest: /etc/mysql/conf.d/client.cnf
      vars:
        password: "{{ mysql_root_password }}"
    - name: symlink .my.cnf file
      file:
        src: /etc/mysql/my.cnf
        dest: /root/.my.cnf
        state: link
    - name: start the MySQL service
      service:
        name: mysql
        state: started
        enabled: true
    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
    - name: Create a new database 'phpbench'
      mysql_db:
        name: phpbench
        state: present

    - name: download composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer
      tags: composer

    - name: install composer
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      args:
        creates: /usr/local/bin/composer
      tags: composer

    - name: rename composer.phar to composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer
      tags: composer

    - name: make composer executable
      file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file
      tags: composer
